### ISSUE TITLE
GitHub 文件 Commits RSS 链接 BUG

### ISSUE THREAD

**Issue by P3TERX** [DIYgod/RSSHub-Radar#10]
刚开始使用，无意中发现BUG

比如这个页面：
https://github.com/DIYgod/RSSHub-Radar/blob/master/README.md

RSSHub-Radar 给出的 RSS 链接是：
https://rsshub.app/github/file/DIYgod/RSSHub-Radar/blob/master/README.md

打开后报错：
```
RSSHub 发生了一些意外:
HTTPError: Response code 404 (Not Found)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

查看[文档](https://docs.rsshub.app/programming.html#文件-commits)发现上面的链接路径中多了`/blob`，正确的链接应该是：
https://rsshub.app/github/file/DIYgod/RSSHub-Radar/master/README.md

**Comment by DIYgod** [comment]
Fixed 请更新插件
