### ISSUE TITLE
Add i18n support and English translation

### ISSUE THREAD

**Issue by hikerpig** [DIYgod/RSSHub-Radar#139]
这个项目这么好，可以推广一番，不如先加上多语言支持。

## UI 改变

1. 设置里面加一个切换语言的下拉菜单。

## 代码设想

1. 用 [vue-i18n](https://kazupon.github.io/vue-i18n/) 作 i18n 框架
2. 语言文件放入 `src/locales/*.json`， 翻译不多的话，webpack 可以一次性都打包进去。
3. 加一个 `js/common/i18n.js` 保留单独的 i18n 实例，这样 js 里面非 Vue 组件内的字符串也能翻译。

**Comment by DIYgod** [comment]
Duplicate of #33
