### ISSUE TITLE
RSSHub Radar for chrome & miniflux

### ISSUE THREAD

**Issue by boeto** [DIYgod/RSSHub-Radar#185]
1.chrome安装RSSHub Radar 后，miniflux页面会自动跳转到登陆页面。禁用RSSHub Radar后，miniflux则恢复正常。不知道是插件和miniflux页面有冲突？
2.firefox已经有“一键订阅到miniflux”，chrome版什么时候可以更新

**Comment by DIYgod** [comment]
1. 理论上不会有冲突，你用的什么版本？
2. Chrome 一直审核不通过，所以我也不知道什么时候可以更新

**Comment by pourley** [comment]
RSSHub Radar:v1.2.1
chrome:79.0.3945.130
miniflux for docker:miniflux/miniflux:latest
---
在firefox一切都好，就是在chrome这样。RSSHub Radar在 chrome设置权限为“点击时”，或者禁用，miniflux页面跳转则正常。

**Comment by DIYgod** [comment]
No idea, but if this problem still exists, feel free to reopen this issue
