### ISSUE TITLE
远程动态加载的规则列表

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub-Radar#19]
规则列表修改频繁，不适合写死在插件中

**Comment by yefoenix** [comment]
@DIYgod 那可以把规则列表文件放到 rsshub repo 里面供大家直接pr了

**Comment by Qixingchen** [comment]
可以加载一系列规则文件么,只使用一个文件容易冲突欸

**Comment by DIYgod** [comment]
@Qixingchen 什么情况下会冲突...

**Comment by Qixingchen** [comment]
多人一起编辑时  
虽然解决冲突也不麻烦(

**Comment by DIYgod** [comment]
@Qixingchen 肯定是托管在 GitHub 上的，冲突就用 git 解决就好了

**Comment by DIYgod** [comment]
Done.
