### ISSUE TITLE
会出现重复

### ISSUE THREAD

**Issue by ImSingee** [DIYgod/RSSHub-Radar#196]
例如 https://reading.developerlearning.cn/reading/

![image](https://user-images.githubusercontent.com/11208082/74602368-aa681400-50e2-11ea-8406-e61694b5ef2f.png)

这两个网址是是完全一样的
https://reading.developerlearning.cn/reading/index.xml
https://reading.developerlearning.cn/reading/index.xml

**Comment by DIYgod** [comment]
确认，需要加个去重逻辑
