### ISSUE TITLE
中文路径处理

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub-Radar#199]
https://github.com/DIYgod/RSSHub/pull/4052

点击复制，得到的链接应该是 encode 之后的

**Comment by junfengP** [comment]
根据论坛上作者的原话，使用`public.php?op=subscribe`对中文无解。(浏览器的锅)

> looks like web browser decodes urlencoded characters in the URL before opening it so tt-rss tries to subscribe to the unescaped URL. if you use subscription form at public.php?op=subscribe field is passed correctly.
>
> i’m not sure if browsers are supposed to do this (maybe?) but i’m certain that trying to urlencode the URL again is a bad idea. not sure what could be done here tbh.

链接：https://community.tt-rss.org/t/api-subscribe-problem-url-contains-chinese-characters/3261

**Comment by junfengP** [comment]
> 根据论坛上作者的原话，使用
对中文无解。(浏览器的锅)
> 
> > looks like web browser decodes urlencoded characters in the URL before opening it so tt-rss tries to subscribe to the unescaped URL. if you use subscription form at public.php?op=subscribe field is passed correctly.
> > i’m not sure if browsers are supposed to do this (maybe?) but i’m certain that trying to urlencode the URL again is a bad idea. not sure what could be done here tbh.
> 
> 链接：https://community.tt-rss.org/t/api-subscribe-problem-url-contains-chinese-characters/3261

通过尝试对中文关键词两次`url encode`， 即  `小米` -> `%e5%b0%8f%e7%b1%b3` -> `%25e5%25b0%258f%25e7%25b1%25b3`。 

`public.php?op=subscribe` 可以订阅带中文的链接。

经过尝试，对关键词做两次`encode`，
或者对关键词做一次`encode`生成`feed url`，对`feed url`再次`encode`， ttrss可以订阅成功。

**Comment by hoilc** [comment]
@junfengP 所以还是得改代码，对ttrss特殊处理下咯，不然虽然${encodeURIComponent(encodeURIComponent(keyword)}可以订阅，但是订阅到其它阅读器会失效

**Comment by hoilc** [comment]
@junfengP https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/popup/index.js#L26 这里encode下是不是就完事了？🤔

**Comment by junfengP** [comment]
> @junfengP 所以还是得改代码，对ttrss特殊处理下咯，不然虽然${encodeURIComponent(encodeURIComponent(keyword)}可以订阅，但是订阅到其它阅读器会失效

是啊，但是我不知道从哪里下手。反正直接对`feed url`进行两次`encode`是不行的，也就是说对`/src/js/popup/index.js`操作是不行的，必须到`/src/js/sandbox/utils.js`下修改`ruleHandler`, 或者`getPageRSSHub`。这么修改对其他阅读器是否造成影响不知道，是否对`verification`字段产生影响也不知道。

**Comment by junfengP** [comment]
> @junfengP https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/popup/index.js#L26 这里encode下是不是就完事了？🤔

或者说在这里，对`feed url`进行两次`encode`， 然后再用` string.replace('%252f','/')`
其中`%252f` -> 是`/`两次编码，还有`:`的两次编码也需要解码

**Comment by hoilc** [comment]
> > @junfengP https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/popup/index.js#L26 这里encode下是不是就完事了？🤔
> 
> 或者说在这里，对`feed url`进行两次`encode`， 然后再用` string.replace('%252f','/')`
> 其中`%252f` -> 是`/`两次编码，还有`:`的两次编码也需要解码

这样也行。

或者也没必要做到完全通用啊，你在这里对`feed_url`做一次encode，应该是不影响正常的订阅的。

然后有中文的像 https://github.com/DIYgod/RSSHub/pull/4052 在规则的`target`里再encode一下，不就两次了（手动滑稽

**Comment by junfengP** [comment]
> > > @junfengP https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/popup/index.js#L26 这里encode下是不是就完事了？🤔
> > 
> > 
> > 或者说在这里，对`feed url`进行两次`encode`， 然后再用` string.replace('%252f','/')`
> > 其中`%252f` -> 是`/`两次编码，还有`:`的两次编码也需要解码
> 
> 这样也行。
> 
> 或者也没必要做到完全通用啊，你在这里对`feed_url`做一次encode，应该是不影响正常的订阅的。
> 
> 然后有中文的像 [DIYgod/RSSHub#4052](https://github.com/DIYgod/RSSHub/pull/4052) 在规则的`target`里再encode一下，不就两次了（手动滑稽

那不是一劳永逸嘛，要不然还得去现在的`radar-rules`里头去找哪些有中文，再改改。工作量就出来了，需要一个印度程序员。 :)

**Comment by hoilc** [comment]
> > > > @junfengP https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/popup/index.js#L26 这里encode下是不是就完事了？🤔
> > > 
> > > 
> > > 或者说在这里，对`feed url`进行两次`encode`， 然后再用` string.replace('%252f','/')`
> > > 其中`%252f` -> 是`/`两次编码，还有`:`的两次编码也需要解码
> > 
> > 
> > 这样也行。
> > 或者也没必要做到完全通用啊，你在这里对`feed_url`做一次encode，应该是不影响正常的订阅的。
> > 然后有中文的像 [DIYgod/RSSHub#4052](https://github.com/DIYgod/RSSHub/pull/4052) 在规则的`target`里再encode一下，不就两次了（手动滑稽
> 
> 那不是一劳永逸嘛，要不然还得去现在的`radar-rules`里头去找哪些有中文，再改改。工作量就出来了，需要一个印度程序员。 :)

刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`

**Comment by junfengP** [comment]
> 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`

大兄弟，憋说了，pr我， ：)

**Comment by hoilc** [comment]
> > 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`
> 
> 大兄弟，憋说了，pr我， ：)

大兄弟先试试？应该没什么副作用吧🤔

[RadarDist.zip](https://github.com/DIYgod/RSSHub-Radar/files/4275516/RadarDist.zip)

**Comment by junfengP** [comment]
> > > 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`
> > 
> > 
> > 大兄弟，憋说了，pr我， ：)
> 
> 大兄弟先试试？应该没什么副作用吧🤔
> 
> [RadarDist.zip](https://github.com/DIYgod/RSSHub-Radar/files/4275516/RadarDist.zip)

订阅到TTRSS可以，但是点击复制，出来的还是未编码滴。

我觉得在复制按钮这里也处理一下比较好，不然还需要手动转码才能用。

**Comment by yefoenix** [comment]
@junfengP 除了 TTRss，还有哪个阅读器需要做 encode 吗？如果没有就不必处理复制按钮吧

**Comment by hoilc** [comment]
> > > > 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`
> > > 
> > > 
> > > 大兄弟，憋说了，pr我， ：)
> > 
> > 
> > 大兄弟先试试？应该没什么副作用吧🤔
> > [RadarDist.zip](https://github.com/DIYgod/RSSHub-Radar/files/4275516/RadarDist.zip)
> 
> 订阅到TTRSS可以，但是点击复制，出来的还是未编码滴。
> 
> 我觉得在复制按钮这里也处理一下比较好，不然还需要手动转码才能用。

复制的为什么需要手动转码呢？ttrss的订阅界面里是支持中文的

**Comment by junfengP** [comment]
![image](https://user-images.githubusercontent.com/15406392/75680282-39bd1c00-5ccc-11ea-886b-1443b67e2fc3.png)

@hoilc 

其他阅读器没有测试过，但是编码后的兼容性更高吧。
包括本issue的一楼是为了处理复制按钮
@yefoenix

**Comment by hoilc** [comment]
> ![image](https://user-images.githubusercontent.com/15406392/75680282-39bd1c00-5ccc-11ea-886b-1443b67e2fc3.png)
> 
> @hoilc
> 
> 其他阅读器没有测试过，但是编码后的兼容性更高吧。
> 包括本issue的一楼是为了处理复制按钮
> @yefoenix

咦，真的不行欸，但是之前我试了[twitter的搜索](https://rsshub.app/twitter/keyword/肺炎)是可以的，虽然标题会有乱码。

那的确还是复制的URL encode一下比较好。

**Comment by junfengP** [comment]
> > > 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`
> > 
> > 
> > 大兄弟，憋说了，pr我， ：)
> 
> 大兄弟先试试？应该没什么副作用吧🤔
> 
> [RadarDist.zip](https://github.com/DIYgod/RSSHub-Radar/files/4275516/RadarDist.zip)

这个版本报错了，具体影响未知。
![image](https://user-images.githubusercontent.com/15406392/75682558-91f61d00-5cd0-11ea-83ad-c42ee2a9ffee.png)

![image](https://user-images.githubusercontent.com/15406392/75682332-36c42a80-5cd0-11ea-9acc-2555187844b3.png)

![image](https://user-images.githubusercontent.com/15406392/75682399-52c7cc00-5cd0-11ea-954d-418676db8d2f.png)

@hoilc @DIYgod

**Comment by hoilc** [comment]
> > > > 刚愣了下，其实`encodeURI(encodeURI(feed_url))`就完事了吧，不需要`encodeURIComponent`
> > > 
> > > 
> > > 大兄弟，憋说了，pr我， ：)
> > 
> > 
> > 大兄弟先试试？应该没什么副作用吧🤔
> > [RadarDist.zip](https://github.com/DIYgod/RSSHub-Radar/files/4275516/RadarDist.zip)
> 
> 这个版本报错了，具体影响未知。
> ![image](https://user-images.githubusercontent.com/15406392/75682558-91f61d00-5cd0-11ea-83ad-c42ee2a9ffee.png)
> 
> ![image](https://user-images.githubusercontent.com/15406392/75682332-36c42a80-5cd0-11ea-9acc-2555187844b3.png)
> 
> ![image](https://user-images.githubusercontent.com/15406392/75682399-52c7cc00-5cd0-11ea-954d-418676db8d2f.png)
> 
> @hoilc @DIYgod

之前也这样，对本地测试应该没啥影响，还有人开issue问的 #190

**Comment by LoneFireBlossom** [comment]
我想订阅一些中文名字的贴吧到inoreader，以前例如
https://rsshub.app/tieba/forum/显卡
这样的是可以用rsshub直接订阅的，
现在不行了，必须是
https://rsshub.app/tieba/forum/%E6%98%BE%E5%8D%A1
这种才行……问了inoreader的客服也说无能为力……所以来找找看有没有解决

**Comment by junfengP** [comment]
目前解决办法就是手动编码中文，因为radar插件无法过审。

浏览器按F12，点console(控制台) 输入 `encodeURI('https://rsshub.app/tieba/forum/显卡')`

@LoneFireBlossom

**Comment by LoneFireBlossom** [comment]
谢谢，另外想问下你说的过审是指什么呢？如果是指应用商店的话，我看chrome商店的版本不是最新版呀，感觉已经不在平台上更新了只能自己手动安装了吧
@junfengP

**Comment by junfengP** [comment]
不过审的意思就是chrome商店无法更新到最新，手动安装重启后会被chrome安全机制给卸载。
@LoneFireBlossom

**Comment by DIYgod** [comment]
06aa9e0bbdb304ae06d0f25efc42bc4623929942 除了 inoreader 都没问题了

FreshRSS 和 Miniflux 没有环境测试

**Comment by LoneFireBlossom** [comment]
> [06aa9e0](https://github.com/DIYgod/RSSHub-Radar/commit/06aa9e0bbdb304ae06d0f25efc42bc4623929942) 除了 inoreader 都没问题了
> 
> FreshRSS 和 Miniflux 没有环境测试

现在inoreader订阅中文名贴吧还是不行，请问近期还有改进的打算么

**Comment by DIYgod** [comment]
> 现在inoreader订阅中文名贴吧还是不行，请问近期还有改进的打算么

inoreader 的问题，建议找 inoreader 客服投诉

**Comment by LoneFireBlossom** [comment]
> > 现在inoreader订阅中文名贴吧还是不行，请问近期还有改进的打算么
> 
> inoreader 的问题，建议找 inoreader 客服投诉

谢谢回复，那我自己手动弄把
