### ISSUE TITLE
火狐插件被下架了

### ISSUE THREAD

**Issue by zoenglinghou** [DIYgod/RSSHub-Radar#215]
The Firefox extension is no longer available in store. Did Mozilla pull some shinenigans again?

**Comment by mr-cn** [comment]
@DIYgod

**Comment by Arragon** [comment]
Release xpi file if possible？ @DIYgod

**Comment by LakeishaKowalczyk** [comment]
here you are

[i@diygod.me.xpi.zip](https://github.com/DIYgod/RSSHub-Radar/files/4518398/i%40diygod.me.xpi.zip)

**Comment by zoenglinghou** [comment]
重新上架了

**Comment by IceCodeNew** [comment]
> 重新上架了

Readme 上的火狐图标链过去的插件页还是显示找不到插件。

https://addons.mozilla.org/zh-CN/firefox/addon/rsshub-radar/
![image](https://user-images.githubusercontent.com/32576256/81580744-6a15ea80-93e0-11ea-9132-495f236839df.png)

**Comment by Arragon** [comment]
名字改了，直接搜索rsshub就能找到

**Comment by DIYgod** [comment]
#212

**Comment by IceCodeNew** [comment]
> #212

推了一个 [PR #278](https://github.com/DIYgod/RSSHub-Radar/pull/278) 来更新 README.md 上链接的火狐插件地址，您确认下新的地址是不是这个：
https://addons.mozilla.org/zh-CN/firefox/addon/rsshub-radar-en/

**Comment by HenryQW** [comment]
@IceCodeNew 这居然还有山寨的…请认准 DIYgod牌…

**Comment by DIYgod** [comment]
叒重新上架了
