### ISSUE TITLE
[Feature Request] 为feed链接页面提供一键订阅功能

### ISSUE THREAD

**Issue by yefoenix** [DIYgod/RSSHub-Radar#22]
如题，当当前页面实际上是一个rss feed链接时，希望也能提供一键订阅到 TTRSS/Feedly/Inoreader 的按钮

**Comment by DIYgod** [comment]
@yefoenix v1.0 已经有了啊，等审核或者安装开发版本

**Comment by DIYgod** [comment]
Done e0ee3fd0a9b1f2fe1d365a4822b9be1340fe4c90
