### ISSUE TITLE
Feedly 不能订阅

### ISSUE THREAD

**Issue by supernova16** [DIYgod/RSSHub-Radar#229]
出现 Feed not found, Wrong feed URL or dead feed 这样的提示

复现例子：

- https://rsshub.app/instagram/user/rmillerphotoeditor
- https://rsshub.app/zhihu/people/pins/hi-id （订阅成功但是 feedly 中获取内容时仍然提示 feed not found）

**Comment by DIYgod** [comment]
反爬严格请自建
