### ISSUE TITLE
求支持百度新闻-基于关键字的订阅

### ISSUE THREAD

**Issue by 1eez** [DIYgod/RSSHub-Radar#243]
比如我想订阅“区块链”关键字的百度新闻。
具体URL如下：
https://www.baidu.com/s?rtt=1&bsst=1&cl=2&tn=news&rsv_dl=ns_pc&word=%E5%8C%BA%E5%9D%97%E9%93%BE

原来百度新闻是支持RSS的，但是现在也不支持了，求RSSHub解救。

**Comment by DIYgod** [comment]
refer to https://github.com/DIYgod/RSSHub/issues/new?template=rss_request_zh.md
