### ISSUE TITLE
希望提供 Microsoft Edge 浏览器插件

### ISSUE THREAD

**Issue by tcitry** [DIYgod/RSSHub-Radar#250]
目前 Edge 已经开放了浏览器扩展，很多官方插件都上架了，希望咱 RSSHub 也能上架 :D

https://microsoftedge.microsoft.com/addons/category/EdgeExtensionsEditorsPick?hl=zh-CN

**Comment by DIYgod** [comment]
https://microsoftedge.microsoft.com/addons/detail/gangkeiaobmjcjokiofpkfpcobpbmnln
