### ISSUE TITLE
您好 可以支持一下 这个网站吗 

### ISSUE THREAD

**Issue by lhj5426** [DIYgod/RSSHub-Radar#253]
尊敬的开发者您好
请问可否支持一下这个网站 sukebei.nyaa 丨nyaa 
我知道这个网站自带RSS
但是请看我把话说完
这个网站支持的RSS 太基本了 只是简单的支持订阅或者搜索关键字订阅
一般来说够用 例如
https://sukebei.nyaa.si/?page=rss&q=%E3%82%B2%E3%83%BC%E3%83%A0CG&c=0_0&f=0
可是有时候会出现讨厌的家伙用你订阅的关键字捣乱 这就很让人难受
我现在就遇到了这种问题
本来我用NYAA订阅的是 ゲームCG 这个关键字 
https://sukebei.nyaa.si/?page=rss&q=%E3%82%B2%E3%83%BC%E3%83%A0CG&c=0_0&f=0
如图
![image](https://user-images.githubusercontent.com/30548000/80202698-9a2b6280-8658-11ea-9f87-86604cc36c8d.png)
订阅这个的目的就是看看每个月日本发售的美少女游戏的CG图片
之前一直将相安无事
直到最近出现了一个讨厌的家伙 也用这个关键字发很多年前的老CG 

![image](https://user-images.githubusercontent.com/30548000/80202971-05753480-8659-11ea-8c9b-d73a08952b39.png)

他发的包含了我订阅的关键字 ゲームCG 并且很规律加了个  Game CG
既然这么规律 那么就在想能不能订阅的时候排除 他这个 Game CG 关键字呢
看到您这个 说万物皆可 RSS那么可以不可以让 sukebei.nyaa 丨nyaa  也加入万物的行列呢这样是不是应该就可以用 filterout_title: 过滤标题 来进行 订阅 关键字 ゲームCG 但同时排除关键字  Game CG 的操作呢 ？
真的挺难受 听困扰的  希望开发者 可以考虑一下 
一个困扰的小白留。

**Comment by DIYgod** [comment]
Refer to https://github.com/DIYgod/RSSHub

**Comment by yefoenix** [comment]
https://siftrss.com
