### ISSUE TITLE
一键订阅Tiny Tiny RSS, 提示 File not found

### ISSUE THREAD

**Issue by JoJoJoinme** [DIYgod/RSSHub-Radar#259]
Tiny Tiny RSS 正常使用，可自行添加订阅
RSS Hub也是正常使用。
配合浏览器插件RSS Radar,提示File not found
浏览器为Chrome 81
Tiny Tiny RSS 版本
如下:
https://rss.helious.xyz/public.php?op=subscribe&feed_url=http://rsshub.app/hexo/yilia/cloudstone.xin

**Comment by hoilc** [comment]
测试没有问题。

![image](https://user-images.githubusercontent.com/9067094/81263794-e6bc6800-9072-11ea-956c-fd2c673f4c0a.png)

**Comment by JoJoJoinme** [comment]
> 测试没有问题。
> 
> ![image](https://user-images.githubusercontent.com/9067094/81263794-e6bc6800-9072-11ea-956c-fd2c673f4c0a.png)

谢谢回复。
看了你的链接，猜出来了。
我的问题应该是搭建Tinty Tiny RSS的时候放到子目录去了。
正常订阅应该是https://mysite.com/
而我的正常订阅为https://mysite.com/tt-rss 
在浏览器扩展中修改后即可正常通过浏览器订阅。

**Comment by shuxuejia** [comment]
> > 测试没有问题。
> > ![image](https://user-images.githubusercontent.com/9067094/81263794-e6bc6800-9072-11ea-956c-fd2c673f4c0a.png)
> 
> 谢谢回复。
> 看了你的链接，猜出来了。
> 我的问题应该是搭建Tinty Tiny RSS的时候放到子目录去了。
> 正常订阅应该是https://mysite.com/
> 而我的正常订阅为https://mysite.com/tt-rss
> 在浏览器扩展中修改后即可正常通过浏览器订阅。

也碰到类似问题，最后怎么解决的啊
