### ISSUE TITLE
微博：无法识别博主

### ISSUE THREAD

**Issue by liyishuai** [DIYgod/RSSHub-Radar#266]
## 版本
v1.4.0
## 环境
- macOS 10.13.6
- Chrome 81.0.4044.129
## 访问页面
http://weibo.com/1195230310/
## 现象
未识别页面对应的订阅源
![image](https://user-images.githubusercontent.com/7020805/81083456-9bfbee00-8ec2-11ea-99f2-3f65a0159a63.png)

**Comment by DIYgod** [comment]
fixed https://github.com/DIYgod/RSSHub/commit/9a1b6ca0cc3538c7f31d56f654b0d2b03f35c2ae
