### ISSUE TITLE
Firefox EvalError: call to eval() blocked by CSP

### ISSUE THREAD

**Issue by MisteryMonster** [DIYgod/RSSHub-Radar#269]
规则请求似乎被Block了，似乎和上次你们讨论的相关 #61 

EvalError: call to eval() blocked by CSP sandbox.js:1:77894
    getList moz-extension://b6964477-90c4-434e-a6b3-6e367f6f361a/sandbox.js:1
    186 moz-extension://b6964477-90c4-434e-a6b3-6e367f6f361a/sandbox.js:1
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). sandbox.js:1:77893

**Comment by MisteryMonster** [comment]
哦我没描述清楚！是在准备调试规则的时候出现的！并不是请求更新！

**Comment by synchrone** [comment]
unless firefox implements WebExtension "sandbox" key - the only way seems to be to allow CSP unsafe-eval by adding 
`"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';",`
to `manifest.json`

**Comment by DIYgod** [comment]
same as #212

**Comment by DIYgod** [comment]
Done e9a8ffeb03421540a7188f9a41dc48df12d24d21
