### ISSUE TITLE
Customize rules

### ISSUE THREAD

**Issue by liyishuai** [DIYgod/RSSHub-Radar#275]
https://github.com/DIYgod/RSSHub-Radar/blob/29c9ea41cc3994298ef3cfee14ab30e849cd62d9/src/js/common/rules.js#L1-L2
Say I want to customize radar rules, _e.g._, have the subscribe button to use `/weibo/user/:uid/1` rather than `/weibo/user/:uid`. Is it worth making the radar rules URL configurable, just like `rsshubDomain`?
https://github.com/DIYgod/RSSHub-Radar/blob/29c9ea41cc3994298ef3cfee14ab30e849cd62d9/src/js/common/config.js#L1-L2

**Comment by DIYgod** [comment]
What's the point? You can create a pull request to `radar-rules.js`

**Comment by liyishuai** [comment]
If it is worth changing Weibo subscribe button to use `/weibo/user/:uid/1` for all users, I can create the PR.
