### ISSUE TITLE
增加 jsdelivr 作为远程规则的 fallback 地址

### ISSUE THREAD

**Issue by letthere-belight** [DIYgod/RSSHub-Radar#279]
找不到怎么解决

**Comment by letthere-belight** [comment]
![image](https://user-images.githubusercontent.com/58315339/81897456-3f4ab280-95e9-11ea-8080-f0b10490ef2c.png)
其他浏览器正常   就QQ浏览器这样

**Comment by DIYgod** [comment]
点 立即更新 会更新么

**Comment by letthere-belight** [comment]
> 点 立即更新 会更新么

会卡在 更新中 然后没反应了

**Comment by letthere-belight** [comment]
> 点 立即更新 会更新么

![image](https://user-images.githubusercontent.com/58315339/82270679-24d95600-99a8-11ea-9295-69685c53bd51.png)
这是qq浏览器应用中心提示的错误

**Comment by DIYgod** [comment]
看起来是网络错误，https://raw.githubusercontent.com/DIYgod/RSSHub/master/assets/radar-rules.js 能打开么

**Comment by letthere-belight** [comment]
打不开

**Comment by DIYgod** [comment]
jsdelivr https://cdn.jsdelivr.net/gh/DIYgod/RSSHub@master/assets/radar-rules.js

**Comment by letthere-belight** [comment]
请问大佬这个会在哪个版本解决  我更新到1.6.1好像还是不行

**Comment by DIYgod** [comment]
106ad2e13be973e2b3ddcb5fb0438a49f8cf04dd
