### ISSUE TITLE
谷歌拓展规则更新显示异常，另很多网站并不显示rss订阅，包括官网的部署

### ISSUE THREAD

**Issue by dihambo** [DIYgod/RSSHub-Radar#297]
![image](https://user-images.githubusercontent.com/35786546/83868102-e8a24580-a75c-11ea-8876-6616a05caf13.png)
![image](https://user-images.githubusercontent.com/35786546/83868310-3b7bfd00-a75d-11ea-950d-f0d0afbe80fe.png)    
B站等等网站都没有反应。。    
大概就是这两种情况

**Comment by DIYgod** [comment]
raw.githubusercontent.com 被墙了 #279
