### ISSUE TITLE
改进自带 RSS 检测规则

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub-Radar#30]
包括

- href 符合 `/\/feed$/` 的 a 标签
- title 符合 `/^rss$/i` 的 a 标签
- a.rss
- 待补充

**Comment by yefoenix** [comment]
atom，xml ?

**Comment by Latias94** [comment]
我觉得可以增加 Feedly 的 [Search API](https://developer.feedly.com/v3/search/) 结果作为参考
例如 csdn 某个博主的 RSS，用插件找不到，用 Feedly 就能搜到 https://cloud.feedly.com/v3/search/feeds/?query=https://blog.csdn.net/ecidevilin/

**Comment by DIYgod** [comment]
@Latias94 API 结果并不总是令人满意，比如 https://cloud.feedly.com/v3/search/feeds/?query=https://weibo.com，返回了很多不需要的结果

对于 csdn 这种情况，增加了 a.rss 作为检测方式

**Comment by DIYgod** [comment]
Done 9dce243df8bd404a76e185641a4bda53ddfc3197 0fb206670f1f5831890ebf6cd82f3c9bc073d3af 0b5a480e995b21fc9a4abba32bdfedbccd95e64d
