### ISSUE TITLE
支持修改规则获取源

### ISSUE THREAD

**Issue by ImSingee** [DIYgod/RSSHub-Radar#32]
目前规则获取是直接从 `https://raw.githubusercontent.com/DIYgod/RSSHub/master/assets/radar-rules.js` 拉取的，这为开发调试和自部署 RSSHub 带来了很大的不方便

**Comment by DIYgod** [comment]
Done 52b0814574825c4c23c9ff5fc243a884f3ff6556

没有支持修改规则获取源，而是支持了手动编辑规则，位置在列表页下方

效果如图
![](https://i.imgur.com/L9m41F7.jpg)
