### ISSUE TITLE
Translation to english?

### ISSUE THREAD

**Issue by shyim** [DIYgod/RSSHub-Radar#33]

**Comment by TriMoon** [comment]
I'm interested in this, but i don't understand a thing because it is all Chinese?

Google translate: 我对此很感兴趣，但是我什么都不懂，因为那全是中国人？

**Comment by djbclark** [comment]
I too would love to see English supported. This sounds like an excellent base on which to sit an open source https://nuzzel.com/ alternative. (Nuzzel makes a top news feed for you based on links shared by friends; it's insanely useful, but looks to be dying, e.g. Facebook support stopped working months ago and hasn't been fixed, so it only support Twitter now.)

**Comment by synchrone** [comment]
Ideally it would be done with JS `i18n`, but in the mean time I ported it as a fork: https://addons.mozilla.org/en-US/firefox/addon/rsshub-radar-en/

(also I'm not a Chinese speaker, so treat this as a best-effort fork)

**Comment by p-bojkowski** [comment]
Any news on this issue?

**Comment by synchrone** [comment]
@p-bojkowski none so far. 
If only there would be someone interested to take on the effort of introducing i18n, I suspect DIYGod would consider merging it.
Wanna do it?

**Comment by DIYgod** [comment]
This issue will be closed because it has been resovled
