### ISSUE TITLE
规则设置显示无法更新

### ISSUE THREAD

**Issue by guoar81** [DIYgod/RSSHub-Radar#335]
Hi

搭配使用 Reader 4 以及 RSSHub Radar给了我极佳的阅读感受。
感谢作者对中文RSS阅读的坚守；
使用 RSSHub的过程中，
MBP（10.15.6） + Chrome （ 84.0.4147.89）能够查阅 RSSHub Radar的文档；
但Mac mini（10.15.6） + Chrome（84.0.4147.89）却无法使用，且点击更新无果。

Mac mini的使用情况，具体见下图：

![截屏2020-07-28 下午4 21 27](https://user-images.githubusercontent.com/68895357/88642836-8ed25200-d0f3-11ea-9d0f-30da66117377.png)

**Comment by DIYgod** [comment]
No idea, but if this problem still exists, feel free to reopen this issue
