### ISSUE TITLE
字幕组详情页中的rss地址没有识别出来

### ISSUE THREAD

**Issue by tgly307** [DIYgod/RSSHub-Radar#36]
例如：http://www.zmz2019.com/resource/37932 
DIY分析：跨域了

**Comment by kt286** [comment]
https://github.com/vitvad/Access-Control-Allow-Origin/blob/master/background.js

**Comment by kt286** [comment]
https://github.com/ionepub/ionepub.github.io/issues/39

**Comment by DIYgod** [comment]
Fixed ca2b82946ecad2448be95906f84894c03f1a04f8
