### ISSUE TITLE
radar插件无法订阅的问题。

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub-Radar#368]
时不时就出现，以前也出现过，但是搞忘记提交了，这次又遇到了就说一下这个。
![image](https://user-images.githubusercontent.com/44609485/91577775-cd219200-e97b-11ea-9027-4b38a95eb124.png)
不知道为啥那个页面就弹不出来，就缩在里面，明明显示可以订阅的，有那个红色的1。
---
![image](https://user-images.githubusercontent.com/44609485/91577788-d27edc80-e97b-11ea-9b8a-c7ae24b36b5c.png)
有时候却又可以。
![image](https://user-images.githubusercontent.com/44609485/91577805-d874bd80-e97b-11ea-90ca-9a03690a1af0.png)
sha上面那个是关闭的问题里面的一个，我刚刚去实验了一下，可以订阅。
![image](https://user-images.githubusercontent.com/44609485/91577840-e32f5280-e97b-11ea-8f7a-744a06b22271.png)
---
关闭了也没关系，就提一下这个，反馈一下这个情况。
---
![image](https://user-images.githubusercontent.com/44609485/91578131-546f0580-e97c-11ea-8628-8022145f64a9.png)
我是自建的，那个ttrss 订阅信息源还可以用，就是对应的来源页面，例如知乎那个插件用不了，订阅不了。

**Comment by DIYgod** [comment]
请检查 v2.0.0 问题是否还存在，如果还存在的话请 reopen 这个 issue

**Comment by YFC0254** [comment]
大神，rsshub radar为b站的UP主制作了rss订阅源，但是在Qi reader显示该地址不是rss订阅源，这种情况该怎么办呢
![Uploading 截图 2024-02-03 19-46-22.png…]()

**Comment by YFC0254** [comment]
大神，rsshub radar为b站的UP主制作了rss订阅源，但是在Qi reader显示该地址不是rss订阅源，这种情况该怎么办呢
![Uploading 截图 2024-02-03 19-50-19.png…]()

**Comment by DIYgod** [comment]
@YFC0254 看不到图片，另外请提供插件版本号和订阅地址

**Comment by YFC0254** [comment]
谢谢美女，这个问题解决了，链接是对的，只是Qi reader不识别这个链接
