### ISSUE TITLE
识别不到掘金的RSS

### ISSUE THREAD

**Issue by busyrat** [DIYgod/RSSHub-Radar#39]
我看 RSSHub [文档](https://docs.rsshub.app/programming.html#%E6%8E%98%E9%87%91)上都有掘金的RSS，但是插件识别不了

![image](https://user-images.githubusercontent.com/20984527/63011561-23c84500-bebb-11e9-9b05-544cf337e2bd.png)

**Comment by Qixingchen** [comment]
还没人写这个规则(

**Comment by DIYgod** [comment]
可以参与我们[提交规则](https://docs.rsshub.app/joinus/#%E6%8F%90%E4%BA%A4%E6%96%B0%E7%9A%84-rsshub-radar-%E8%A7%84%E5%88%99)
