### ISSUE TITLE
为啥不识别logseq？

### ISSUE THREAD

**Issue by kunpeng9** [DIYgod/RSSHub-Radar#395]
网站描述
A local-first knowledge base which can sync using Github.
一个本地优先的知识库，可以使用 Github 同步。
内容？
https://logseq.com/blog/latest.rss，如下图，没有反应，虽然在tiny rss里面可以添加这个订阅，添加成功了。
![image](https://user-images.githubusercontent.com/44609485/94931461-5cc9db80-04fa-11eb-8f15-457155b20b9e.png)
额外描述

**Comment by DIYgod** [comment]
Not sure why, this RSS is not recognized correctly by Chrome, so RSSHub radar didn't recognise it also.
