### ISSUE TITLE
Firefox 上无法自动更新规则，显示自动更新已禁用

### ISSUE THREAD

**Issue by SylleoYr** [DIYgod/RSSHub-Radar#408]
如题，在 MS Edge 上正常，搜索了一下 issue，似乎没有发现相关 issue，如果是我错过了相关 issue，可以帮我贴出来吗？谢谢。

**Comment by zoenglinghou** [comment]
似乎是 mozilla 的规定之类的，解决方法可能是要督促作者多更新😂

**Comment by iSteveyang** [comment]
[写得很清楚了](https://github.com/DIYgod/RSSHub-Radar/releases/tag/v1.6.0)
用1.6.0前的吧

**Comment by zoenglinghou** [comment]
@iSteveyang 这就很尴尬了...我给这个插件提了个支持 Nextcloud News 的 PR，还等着作者 Release 呢... 其实都到用旧版的地步了，不如自己编译一个（

**Comment by iSteveyang** [comment]
嗯，我也尝试过
npm编译1.6.1的时候报错，也许是库环境问题
你有修改后的fork可供参考吗？

**Comment by zoenglinghou** [comment]
我 build `master` 和 `v1.6.1` 都没有问题耶
OS: Ubuntu 20.04
yarn: v1.22.10
node: v15.14.0

**Comment by DIYgod** [comment]
加上自动更新ff审核不通过，很无奈😂

**Comment by yindaheng98** [comment]
我这编译没问题，倒是用的时候设置页打不开 #632 #633

**Comment by iSteveyang** [comment]
> 加上自动更新ff审核不通过，很无奈😂

大佬，FF能否提供自动更新版，我直接本地安装

**Comment by zoenglinghou** [comment]
@iSteveyang 其实本地安装重启的话不是要重装吗？不过我安装 tridactyl beta 版的时候并不用重装…不知道火狐到底是什么逻辑

**Comment by zoenglinghou** [comment]
> 加上自动更新ff审核不通过，很无奈😂

指的是自动更新规则还是 CI 编译的插件？

**Comment by SylleoYr** [comment]
> 
> 
> 加上自动更新ff审核不通过，很无奈😂

好吧🤣

**Comment by edr1412** [comment]
为什么我手动覆盖规则后还是会被旧版本重置？Firefox用户怎样才能改规则？

**Comment by DIYgod** [comment]
Firefox does not allow extensions to use eval, so Firefox's remote rule updates are disabled, this is not a thing we can fix, so this issue will be closed.
