### ISSUE TITLE
希望“一键订阅”设置里“inoreader”提供可选项

### ISSUE THREAD

**Issue by DustinShaw** [DIYgod/RSSHub-Radar#421]
目前inoreader提供了更快的镜像站点jp.inoreader.com，而RSSHub-Rader提供的inoreader订阅选项依然只使用www.inoreader.com的链接进行订阅，导致每次都需要重新登录inoreader，并且默认的www.inoreader.com很慢，几乎不能用。

所以，希望您能提供inoreader订阅设置的选项，这样我可以选择是使用www.inoreader.com还是jp.inoreader.com抑或us.inoreader.com来订阅我的RSS Feed，而不用忍受每次都要登录并且极慢的速度。

谢谢您的付出！

**Comment by DIYgod** [comment]
Done. ff0a9c24cf517378f27b57950469273b15a4e374
