### ISSUE TITLE
無法透過RSSHub-Radar 追蹤 Instagram 用戶

### ISSUE THREAD

**Issue by marklin0913** [DIYgod/RSSHub-Radar#426]
打開Instagram 用戶頁面按下擴充元件後，擴充元件有顯示該IG用戶的RSS Feed的連結，但是進入該連結的時候，卻顯示錯誤，已試過多個不同的IG帳號，結果都是相同的。（圖片中帳號為: _canonusa_ )

![螢幕截圖](https://i.imgur.com/rIqaMbP.png)
## 系統資訊
* **Firefox 82.0 64bit**
* **RSS-Hub-Radar 版本1.6.0**
* Manjaro Linux

**Comment by unaya** [comment]
RSSHub 已经移除了对 instagram 的支持，参见https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-645761284
扩充插件仍然显示链接可能是没有更新规则
如果你需要通过 rss 订阅 instagram , 可以参考这个项目 https://sr.ht/~cadence/bibliogram/ ， 以及它的实例https://bibliogram.art/

**Comment by marklin0913** [comment]
非常感謝你的回覆。
我剛剛有查看了Firefox提供的版本仍然為1.6.0而RSSHub-Radar最新的版本已是1.6.1。
