### ISSUE TITLE
规则代码不完整

### ISSUE THREAD

**Issue by 9Panda3** [DIYgod/RSSHub-Radar#460]
![Snipaste_2020-11-26_09-47-23](https://user-images.githubusercontent.com/61393145/100298579-718f9080-2fcc-11eb-8b17-8194bada508d.png)
站酷用户作品的zcool不完整导致无法正常订阅。

**Comment by DIYgod** [comment]
For rule-related questions, please submit an issue to [RSSHub](https://github.com/DIYgod/RSSHub).
