### ISSUE TITLE
无法添加有访问控制密钥的源到 Feedly

### ISSUE THREAD

**Issue by soraros** [DIYgod/RSSHub-Radar#509]
Feedly 会把
`https://feedly.com/i/subscription/feed/https://rsshub.app/qdaily/column/59?key=ILoveRSSHub`
编码成
`https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Frsshub.app%2Fqdaily%2Fcolumn%2F59`
直接把 query string 的部分扔掉。

**Comment by DIYgod** [comment]
请检查 v2.0.1 问题是否还存在，如果还存在的话请 reopen 这个 issue
