### ISSUE TITLE
关于Chrome上安装插件遇到的bug

### ISSUE THREAD

**Issue by ghost** [DIYgod/RSSHub-Radar#532]
使用Firefox测试了相同的crx文件，可以正常使用（指的是可以正常的获取rss链接）；但是为什么同样的插件，放到chrome浏览器上，也能安装上，可以显示角标，可以打开“选项”，但就是不工作，打开同样的网址不起作用。

Chrome浏览器：
![QQ截图20210225183756](https://user-images.githubusercontent.com/36817450/109141371-a01e3280-7798-11eb-904c-49295ff1354b.png)

当时安装时还出现一个警告，两个错误
`Unrecognized manifest key 'applications'.

……

 **"applications": {
        "gecko": {
            "id": "i@diygod.me"
        }
    },**
 
Uncaught (in promise) TypeError: Failed to fetch
Uncaught TypeError: Failed to construct 'URL': Invalid URL
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

能不能给解决下，还有用firefox可以在拓展商店里搜Rsshub Radar，但是用下载的source和release里的文件都用不了。

**Comment by DIYgod** [comment]
Maybe related to #700, if you still have problem, feel free to reopen this issue.
