### ISSUE TITLE
新版的 Tiny Tiny RSS 订阅链接改了

### ISSUE THREAD

**Issue by ptsa** [DIYgod/RSSHub-Radar#556]
老的是
https://xxxxxx/public.php?op=subscribe&feed_url=
新的是
https://xxxxxx/public.php?op=bookmarklets--subscribe&feed_url=

**Comment by pianshanchou** [comment]
确实现在RSSHUB无法使用一键订阅到TTRSS的功能了

**Comment by zpengcom** [comment]
chrome插件为啥还不更新啊

**Comment by xcdler** [comment]
是这样的，新安装的ttrss无法使用插件了 sad :)

**Comment by CoelacanthusHex** [comment]
@DIYgod 希望能发个新版，把这个修复推送下
