### ISSUE TITLE
Try to avoid using eval

### ISSUE THREAD

**Issue by QuantumGhost** [DIYgod/RSSHub-Radar#61]
After skimming the code base, I found that RSSHub Rader [loading  javascript](https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/common/rules.js#L2) from a remote server and [using `eval` to convert it to rules](https://github.com/DIYgod/RSSHub-Radar/blob/master/src/js/common/rules.js#L16). I believe this is a potential security vulnerability. [Mozilla's security best practices](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Security_best_practices) explicitly states that we should not inject or incorporate remote scripts. I think there should be a better approach for retrieving rule updates.

**Comment by DIYgod** [comment]
Of cource eval is not a good way, but it's the only way I can figure out to retrieving rule updates.
Discussion and pull request are welcomed if you have a better idea.

**Comment by QuantumGhost** [comment]
I propose three ways to get rid of `eval`.

One is to use regular expression, which is fairly limited. However, I'm not sure all rules could be written in regex. Also, the maintenance complexity of regex should also be considered.

The second option is, instead directly using `eval`, we use another scripting language which could be interpreted in JS, and limit the capability of the interpreter. Something I think worth looking at is  https://github.com/NeilFraser/JS-Interpreter.

The third one is to rely on sandboxing API provided by browser. For example Chrome has a way to [sandbox `eval`](https://developer.chrome.com/apps/sandboxingEval). I'm not sure whether Firefox has equivalent mechanism. (Or can we just generalize the idea behind Chrome's sandboxing method, put rules in a separate web page and using `postMessage` APIs to evaluate those messages?)
