### ISSUE TITLE
feature request: 增加自定义radar-rules.js文件地址的功能

### ISSUE THREAD

**Issue by yindaheng98** [DIYgod/RSSHub-Radar#634]
RSSHub中提供的radar-rules.js文件有时满足不了需求

比如我在通过RSSHub-Radar订阅`https://rsshub.app/twitter/user/XXXX`的时候想默认添加参数`routeParams=exclude_replies`

在RSSHub原仓库里改显然不行，于是把radar-rules.js单独放在了一个repo用于修改

那么想要在RSSHub-Radar里用上我自己改好的radar-rules.js就需要修改RSSHub-Radar中的radar-rules.js文件地址

RSSHub-Radar现在没有这个功能

**Comment by DIYgod** [comment]
This feature has been implemented in v2.
