### ISSUE TITLE
腾讯视频  剧集无法识别

### ISSUE THREAD

**Issue by joyous-coder** [DIYgod/RSSHub-Radar#641]
# 测试地址
https://v.qq.com/x/cover/mzc00200eacw05k/v0036502bcl.html
# 使用浏览器
Edge  91.0.864.59 (官方内部版本) (64 位)
# 插件版本
 v1.6.0

**Comment by DIYgod** [comment]
For rule-related questions, please submit an issue to [RSSHub](https://github.com/DIYgod/RSSHub).
