### ISSUE TITLE
RSSHub-Radar 在Firefox下无法使用

### ISSUE THREAD

**Issue by line2** [DIYgod/RSSHub-Radar#660]
![图片](https://user-images.githubusercontent.com/65969077/135455180-32cd23e6-7445-4898-b892-62ef99efa943.png)

```
firefox -version

 Mozilla Firefox 92.0.1
```

**Comment by 1078249029** [comment]
Firefox版本 96.0.1 rader版本 1.7 均为最新版 
订阅b站时出现图示情况

**Comment by DIYgod** [comment]
These problems have been resolved and will be released in the next version, if you still have problems please reopen this issue
