### ISSUE TITLE
采用各种方法后依然无法订阅到ttrss

### ISSUE THREAD

**Issue by razyzhang123** [DIYgod/RSSHub-Radar#662]
![image](https://user-images.githubusercontent.com/92351174/136888585-71d576e0-e45b-44f1-9e4b-9cdc96d7897c.png)

{"error":{"code":13,"message":"\u627e\u4e0d\u5230\u65b9\u6cd5(Method)"}}

启动了bookmarklets插件之后不行，也使用了某位大神自己编译的插件还是不行，请问这个问题到底要怎么解决？谢谢了

**Comment by zhpjy** [comment]
相同问题，解决方法是更新ttrss。
由于ttrss的api改过，rsshub-radar适配了最新的ttrss的api。chrome里的插件是自己更新的。最新的rsshub-radar和旧版的ttrss就会出现这个报错
