### ISSUE TITLE
是选项页面有 bug 还是不兼容 vivaldi 呢？

### ISSUE THREAD

**Issue by yichangshengwu** [DIYgod/RSSHub-Radar#664]
如图：

![截图_2021-10-23_22-28-10](https://user-images.githubusercontent.com/43059917/138560780-526f53af-33bb-45bb-85fd-a763d9988da2.png)

系统是 arch linux stable，已经滚到最新，
在 vivaldi 上（经由谷歌商店）安装插件后发现无法打开选项页面，
尚未尝试其他操作，

因为 vivaldi 自己也有 rss 相关的选项，所以想知道是不是不支持呢？

**Comment by Orisik** [comment]
我也是这样!

**Comment by DIYgod** [comment]
v2.0.0 重构后测试可以正常使用
