### ISSUE TITLE
Twitter用户时间线订阅对部分twitter用户有问题

### ISSUE THREAD

**Issue by xmfbit** [DIYgod/RSSHub-Radar#668]
从Chrome市场安装，对下列Twitter用户生成的RSS订阅网址有问题：

- PyTorch：[主页](https://twitter.com/PyTorch)

提示：https://rsshub.app/twitter/user/PyTorch

但应该为：https://rsshub.app/twitter/user/pytorch

也就是改成小写。

**Comment by DIYgod** [comment]
It seems to have no effect, if you still have a problem, feel free to reopen this issue.
