### ISSUE TITLE
[bug] 与类似"网盘助手"一类的扩展有冲突

### ISSUE THREAD

**Issue by Max33Verstappen** [DIYgod/RSSHub-Radar#671]
安装了“网盘助手”或者“购物党自动比工具”之类的扩展之后，就有极大的概率检测不到网页有RSS，在我的使用环境中，大约是刷新网页10次可能只能检测到1～2次。
禁用了”网盘助手”检测到的概率大大提升，然后禁用“购物党自动比价工具”，检测概率又有进一部提升。
可能还有其他扩展与这个有冲突，没有时间一一测试了。

**Comment by DIYgod** [comment]
请检查 v2.0.0 问题是否还存在，如果还存在的话请 reopen 这个 issue
