### ISSUE TITLE
在安卓手机的kiwi浏览器上无法使用吗？

### ISSUE THREAD

**Issue by danmo66** [DIYgod/RSSHub-Radar#672]
kiwi浏览器也是chrome内核，支持直接从Chrome网上应用店安装扩展，但安装了之后无论打开哪个网页都不显示支持的rss

**Comment by 1078249029** [comment]
> kiwi浏览器也是chrome内核，支持直接从Chrome网上应用店安装扩展，但安装了之后无论打开哪个网页都不显示支持的rss

我个人使用也不支持kiwi，改成桌面的UA也不行
只要不是那么急，还是改成PC端使用吧

**Comment by DIYgod** [comment]
不清楚是 v2.0.0 重构的原因还是 kiwi 的原因，现在使用正常
