### ISSUE TITLE
English language option for the Chrome extension

### ISSUE THREAD

**Issue by oliroe** [DIYgod/RSSHub-Radar#674]
Hi

Great work by the way. Any chance of an English language option for the Chrome extension?

Thanks

**Comment by schaafjs** [comment]
Any updates on this? Would also love an english version of the app. I would be happy to contribute to the translation.

---

用谷歌翻译翻译：这有什么更新吗？ 也会喜欢该应用程序的英文版。 我很乐意为翻译做出贡献。

**Comment by DIYgod** [comment]
This issue has been resolved, so now close
