### ISSUE TITLE
【功能建议】能不能把 RSSHub-Radar 的图标放进 Firefox 的地址栏里？

### ISSUE THREAD

**Issue by Kukmoon** [DIYgod/RSSHub-Radar#681]
如图所示。

![图片](https://user-images.githubusercontent.com/16938012/158388593-63c43abf-cbf4-4b15-b5d0-c47d07a10e96.png)

我以前用过一个 Firefox 扩展，好像叫 RSSAtom ，记不清了。如果它检测到当前页面有 RSS，就会显示在 Firefox 的地址栏右侧，如果当前页面没有 CSS，它就不显示。就像早期内置 RSS 订阅器和阅读器的 Firefox 那样。如果 RSSHub-Radar 也有这个特性该多好啊！

**Comment by DIYgod** [comment]
It should have one, it seems to be a bug, I'm not sure if this bug still exits, if so, please reopen this issue.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8266075/212560331-8d532736-1b5b-465f-b897-bebf3f28e1a4.png">
