### ISSUE TITLE
edge浏览器的bilibili不能显示订阅源

### ISSUE THREAD

**Issue by fwqaaq** [DIYgod/RSSHub-Radar#683]
> 在`edge 99.0.1150.46`版本的b站中,不能显示出任何rss的订阅源

* 并且在和谷歌相同的插件的情况下,谷歌完全没有任何问题
![edge](https://user-images.githubusercontent.com/82551626/159922771-782980b1-7c4f-473e-b0a9-dbd8abdfff8b.png)

**Comment by DIYgod** [comment]
Related to #700, this issue has been resolved

**Comment by fwqaaq** [comment]
> Related to #700, this issue has been resolved

Thank you very much, @DIYgod ❤️
