### ISSUE TITLE
求支持中华医学会系列杂志订阅

### ISSUE THREAD

**Issue by TYHDLY** [DIYgod/RSSHub-Radar#686]
期刊目录见：[中华医学会官网期刊列表](http://medjournals.cn/serialjournal/getAllJournals.do?type=1)
每本期刊主页都会有当期目录，如下图：
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/71576832/160428693-c011b29b-fb09-40d5-9cf0-036946905bd8.png">
如果能即时获得每篇文献的题录，最好能抓取免费文献的全文和收费文献的摘要，感谢！🙏

**Comment by DIYgod** [comment]
For rule-related questions, please submit an issue to [RSSHub](https://github.com/DIYgod/RSSHub).
