### ISSUE TITLE
Almost entirely broken on Firefox

### ISSUE THREAD

**Issue by Rongronggg9** [DIYgod/RSSHub-Radar#687]
### Broken UI
![](https://user-images.githubusercontent.com/15956627/161185991-c9b2fb1d-a151-4167-8241-e91c3cdb660c.png)

### Broken rules
1. By default, nothing
![](https://user-images.githubusercontent.com/15956627/161186157-8b2dc87f-8e0b-4014-8299-7e6d73347718.png)
2. Try to fill in something (from https://github.com/DIYgod/RSSHub/blob/gh-pages/build/radar-rules.js)
![](https://user-images.githubusercontent.com/15956627/161186527-9edb91be-b99d-4ebb-866b-c93186ad78fc.png)
3. Refresh, only to find nothing was saved (deleting the brackets won't help)
![](https://user-images.githubusercontent.com/15956627/161186640-1cb304db-1f37-45a2-8c65-c7de7771554a.png)

### FYI
Firefox 98.0, tested on Windows and Debian
RSSHub Radar 1.7.0 from Firefox Add-ons (I've not tested RSSHub-Radar@`master`, since after checking the commit history I believe there is no such need)

**Comment by DIYgod** [comment]
These problems have been resolved, if you still have problems please reopen this issue

**Comment by Rongronggg9** [comment]
> These problems have been resolved

I don't think 99ba987ad31e114ae242c09c16d3e45e6f38d612 has "resolved" the custom rules issue. If custom rules are disabled, debugging new rules is impossible. Still neither prompt nor disabled input box is present to inform newbies about that, right?

> please reopen this issue

An issue closed by repo owner cannot be reopened by its author. I am OK with keeping this issue closed, though, as #691 is still open.

**Comment by DIYgod** [comment]
Oh you are right, just fixed in e5d3801f86e68c28fb115c3c2c626ef634ed0f6d
