### ISSUE TITLE
Gmail feed 

### ISSUE THREAD

**Issue by mbhkoay** [DIYgod/RSSHub-Radar#706]
Gmail feed should be 
https://mail.google.com/mail/feed/atom
not https://mail.google.com/mail/u/0/#inbox/feed/atom

For labels it should be:-
https://mail.google.com/mail/feed/atom/labels
not https://mail.google.com/mail/u/0/#label/labels/feed/atom

Edited to add reference: https://developers.google.com/gmail/gmail_inbox_feed

**Comment by DIYgod** [comment]
Fixed in f5d4c5d5f7aca96da7acdf5d3531b7c91c497e2c
