### ISSUE TITLE
[Feature Request] Add feed preview feature

### ISSUE THREAD

**Issue by anyone00** [DIYgod/RSSHub-Radar#709]
Enable a feed preview when visiting a feed page. Currently when visiting a feed it shows raw XML or JSON.

Adding a little bit of styling to make it more readable.

Firefox does have some extensions for this but none of them support chrome:
- [Feed Preview](https://hg.guido-berhoerster.org/addons/firefox-addons/feed-preview/)
- [RSS Preview](https://github.com/aureliendavid/rsspreview/)
- [Livemarks](https://github.com/nt1m/livemarks/)

**Current behavior**: 
![chrome preview RSS feed](https://user-images.githubusercontent.com/41706133/183399678-63e808d6-556e-4628-a49d-bdfbcd32e618.png)

**Suggested behavior**:
![rss preview RSS feed preview](https://user-images.githubusercontent.com/41706133/183400036-f0d24857-cb23-4536-b462-cd4ea1a357a9.png)
![feed preview RSS feed preview](https://user-images.githubusercontent.com/41706133/183400066-39bd4f8b-b058-4e56-bf7e-7b961242a6fd.png)
![livemarks RSS feed preview](https://user-images.githubusercontent.com/41706133/183400882-e7eda45d-56f5-4b43-ac6c-7cf3d601ea0d.png)

**Comment by DIYgod** [comment]
This function is beyond the purpose of this project.
