### ISSUE TITLE
订阅到TTRSS，会重复订阅

### ISSUE THREAD

**Issue by junfengP** [DIYgod/RSSHub-Radar#71]
### 插件来源
chrome应用市场 版本号：v1.2.0

### radar设置
![image](https://user-images.githubusercontent.com/15406392/64902905-c22a0f00-d6e2-11e9-95a7-7f5f21f3129a.png)

### 订阅页面
youtube 频道
https://www.youtube.com/channel/UCAWnuGH5fKJKM-DiWrdbgJA

### 出现结果
![image](https://user-images.githubusercontent.com/15406392/64902962-89d70080-d6e3-11e9-8a80-3f7e36635d55.png)

订阅的结果会出现两个
![image](https://user-images.githubusercontent.com/15406392/64902929-074e4100-d6e3-11e9-9191-c20e11d283e8.png)

### 尝试重复订阅
![image](https://user-images.githubusercontent.com/15406392/64902951-5ac08f00-d6e3-11e9-8115-658fbb275bce.png)

### TTRSS版本号以及部署方式
通过官方教程部署
版本号：Tiny Tiny RSS v19.2 (1a484ec)

不知道这个BUG是TTRSS的还是radar的

**Comment by DIYgod** [comment]
同 Tiny Tiny RSS v19.2 无法复现

实际上 radar 做的只是访问 Tiny Tiny RSS 的页面，没有额外操作，目测是 Tiny Tiny RSS 的 bug
