### ISSUE TITLE
Pixiv shows the user's dynamic button, which is actually the user's collection

### ISSUE THREAD

**Issue by oldmenplus** [DIYgod/RSSHub-Radar#72]
Pixiv shows the user's dynamic button, which is actually the user's collection

pixiv显示用户动态的按钮，实际上是用户收藏的链接

**Comment by DIYgod** [comment]
Fixed https://github.com/DIYgod/RSSHub/commit/cc01340fb4f3c8b62fb44152baf3ad072576decd
