### ISSUE TITLE
火狐里怎么更新规则

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [DIYgod/RSSHub-Radar#722]
![图片](https://user-images.githubusercontent.com/14090545/205329822-691262af-2629-4f0e-bb24-e9c8d7a64e74.png)

**Comment by LakeishaKowalczyk** [comment]
哭哭

![图片](https://user-images.githubusercontent.com/14090545/210907481-5a528489-f031-41cc-9183-c5dc196ce040.png)

**Comment by DIYgod** [comment]
Firefox does not allow extensions to use eval, so Firefox's remote rule updates are disabled, this is not a thing we can fix 🥹

**Comment by LakeishaKowalczyk** [comment]
@DIYgod 可以支持离线导入吗？

**Comment by DIYgod** [comment]
No, any dynamic update is not possible
