### ISSUE TITLE
Download safari version from app store at China mainland was forbidden

### ISSUE THREAD

**Issue by lixiao189** [DIYgod/RSSHub-Radar#729]
Recently I cannot download safari extension from China mainland region on apple app store.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/44799572/225535020-9d701e8e-a39c-4331-ad69-97bd63807be5.png">

**Comment by Gitbreast** [comment]
Same. Couldn’t download from Hong Kong region either.

**Comment by lixiao189** [comment]
> Same. Couldn’t download from Hong Kong region either.

Even I using apple ID which I registered in American region, it still cannot download it either.

**Comment by heemoe** [comment]
Same

**Comment by DIYgod** [comment]
Sorry for the late reply, it has already been restored.

**Comment by lixiao189** [comment]
Thank you!
在 2023年12月15日 +0800 23:01，DIYgod ***@***.***>，写道：
