### ISSUE TITLE
Radar无法查找出小众软件AppInn的rss

### ISSUE THREAD

**Issue by hxhacking** [DIYgod/RSSHub-Radar#730]
- [最新帖子](https://meta.appinn.net/posts.rss)
- [最新话题](https://meta.appinn.net/latest.rss)

扫描不到分类和标签的rss，比如

- [最新讨论分享话题 - 小众软件官方论坛](https://meta.appinn.net/c/discuss-and-share/6) 对应的 [讨论分享 - rss](https://meta.appinn.net/c/discuss-and-share/6.rss)
- [最新macos话题 - 小众软件官方论坛](https://meta.appinn.net/tag/macos) 对应的 [macos - rss](https://meta.appinn.net/tag/macos.rss)

**Comment by DIYgod** [comment]
现在看是好的了，估计是他们网站修复了

**Comment by hxhacking** [comment]
感谢回复 🙏
