### ISSUE TITLE
ezone.hk not working 不能用

### ISSUE THREAD

**Issue by sammlyu** [DIYgod/RSSHub-Radar#742]
Looks like something went wrong
Route requested: /
Error message: write EPROTO C0E78C8FD07F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:922:
: target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /
Node version: v18.17.0
Git Hash: 5e655eb
        
If you believe this is an error caused by RSSHub, please [report on github](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml)
如果您认为 RSSHub 导致了该错误，请在 GitHub 按照模版，复制本页面信息进行 [汇报](https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml)

這是我用 https://rsshub.app/ezone 出現的問題, 好像由 3 月開始就用不了。可以更新嗎?

**Comment by DIYgod** [comment]
Please go to RSSHub https://github.com/DIYgod/RSSHub
