### ISSUE TITLE
always slow updating rules?

### ISSUE THREAD

**Issue by rezad1393** [DIYgod/RSSHub-Radar#749]
I installed this addon on brave (chrome-based) 

I see in its addon page this 
![Screenshot_20230926_125808-1](https://github.com/DIYgod/RSSHub-Radar/assets/7523164/37fbb65e-e0b7-4200-b517-f6136a000cdd)

it moved by .01% every second .

it is an update or a timer?

when i click update now, it goes to zero again.

**Comment by DIYgod** [comment]
This is a timer that will automatically update when it reaches 0.

**Comment by AiraNadih** [comment]
I believe that the current layout and design of the page elements are quite confusing and misleading. Therefore, I would like to propose some modifications:

1. Visually distinguish the "Update Now" button, the progress bar, and the update time information more clearly.
2. The progress bar should be used to represent the current update status. For example, use different colors or labels to clearly indicate statuses like "Updating" or "Complete."
3. Express the update time in a more intuitive way. For example, use phrases like "xx hours xx minutes until the next automatic update" and "last updated xx hours xx minutes ago" to avoid ambiguity.
