### ISSUE TITLE
大佬，海外主要基金的见解分享有订阅的方式吗？

### ISSUE THREAD

**Issue by niannianjun** [DIYgod/RSSHub-Radar#751]
大佬，海外主要基金的见解分享有订阅的方式吗？
比如https://www.oaktreecapital.com/insights
https://[doubleline.com](https://doubleline.com/)/

**Comment by DIYgod** [comment]
请移步 RSSHub https://github.com/DIYgod/RSSHub

**Comment by niannianjun** [comment]
![image](https://github.com/DIYgod/RSSHub-Radar/assets/131518332/fcdb6aea-ef87-4123-8489-77ad8f9f1c65)
会显示监测不到，是我的用法问题吗
