### ISSUE TITLE
路由参数追加失败

### ISSUE THREAD

**Issue by 9k001** [DIYgod/RSSHub-Radar#752]
情况描述：
    对于某些网站的路由，需要统一追加 routeParams 进行订阅。
如: 微博博主url
原始规则:
```
{ title:"博主",
        docs:"https://docs.rsshub.app/routes/social-media#wei-bo",
        source:[ "/u/:id",
          "/:id" ],
        target:(params, url, document) => {
                    let uid = document?.documentElement.innerHTML.match(/\$CONFIG\['oid']='(\d+)'/)?.[1];
                    if (!uid && !isNaN(params.id)) {
                        uid = params.id;
                    }
                    return uid ? `/weibo/user/${uid}` : '';
                } },

```
统一追加 routeParams
如:
```
/readable=1&showEmojiInDescription=1&showLinkIconInDescription=0
```
使得 通过 RSSHub Radar 进行订阅时自动追加参数，无需手动的接入

当前问题：
将上述代码修改为
```
{ title:"博主",
        docs:"https://docs.rsshub.app/routes/social-media#wei-bo",
        source:[ "/u/:id",
          "/:id" ],
        target:(params, url, document) => {
                    let uid = document?.documentElement.innerHTML.match(/\$CONFIG\['oid']='(\d+)'/)?.[1];
                    if (!uid && !isNaN(params.id)) {
                        uid = params.id;
                    }
                    return uid ? `/weibo/user/${uid}/readable=1&showEmojiInDescription=1&showLinkIconInDescription=0` : '';
                } },

```
通过  RSSHub Radar 进行订阅
- 浏览器地址栏 中URL 正确
- RSSHub Radar 中 '复制' 按钮 复制正确
- 订阅到 TTRSS 后弹出网页 中 'Feed or site URL:'  填写错误。

  将 正常
  ```
  /weibo/user/${uid}/readable=1&showEmojiInDescription=1&showLinkIconInDescription=0
  ```
  中
  ```
  &showEmojiInDescription=1&showLinkIconInDescription=0
  ```
 完全截取掉。
我判断可能是存在某种转义的问题，尝试添加 '\' 无法解决问题。依旧被截取
请问这个问题该如何解决

**Comment by DIYgod** [comment]
每个人需求不同，routeParams 需要手动添加

转义问题请帮看下 v2.0.0 新版本是否还存在，还有的话请 reopen 这个 issue

**Comment by 9k001** [comment]
> 每个人需求不同，routeParams 需要手动添加
> 
> 转义问题请帮看下 v2.0.0 新版本是否还存在，还有的话请 reopen 这个 issue

简单的使用了一下 v2.0.0 新版本，发现并没有自定义规则这个原有的功能。。。
是不是已经关闭了该功能？

**Comment by DIYgod** [comment]
v2 增加了自定义远程规则地址的功能，可以通过自定义为你自己的地址来进行自定义规则

**Comment by 9k001** [comment]
> v2 增加了自定义远程规则地址的功能，可以通过自定义为你自己的地址来进行自定义规则

我看到了相关设置。
我理解，如果按照 rsshub官方提供的规则，应该结合自身的需求，自行生成一个规则js订阅即可。
我的问题是，类似于微博等固定的地址，是不是大概率上基本上是不变的。

**Comment by 9k001** [comment]
> v2 增加了自定义远程规则地址的功能，可以通过自定义为你自己的地址来进行自定义规则

我看到了相关设置。
我理解，如果按照 rsshub官方提供的规则，应该结合自身的需求，自行生成一个规则js订阅即可。
我的问题是，类似于微博等固定的官方的规则，是不是基本上是不变的。这个其实牵扯到我是追加合并还是需要再复杂一点进行逻辑渲染。
不知道实际情况是如何的

**Comment by DIYgod** [comment]
你的规则内容需要基于并包含官方的规则，否则结果是不完整的

**Comment by 9k001** [comment]
> 每个人需求不同，routeParams 需要手动添加
> 
> 转义问题请帮看下 v2.0.0 新版本是否还存在，还有的话请 reopen 这个 issue

我测试了一下，还是有转移的问题。
我是这样的一个流程。
下载 标准的 https://rsshub.js.org/build/radar-rules.js 规则，使用python替换中间的某项如前述所说weibo。并推送至远端代码库。
使用raw.xxxxx.com/xxx/radar-rules.js 进行Rader的自定义规则设置
标准 radar-rules.js 如下
```
/weibo/user/${uid}
```
修改为
```
/weibo/user/${uid}/readable=1&authorNameBold=1&showAuthorInTitle=0&showAuthorInDesc=1&showAuthorAvatarInDesc=0&showAuthorAvatarInDesc=0&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=0&showEmojiInDescription=1&showLinkIconInDescription=0&showLinkIconInDescription=0&key=geRSAaJrwdXyDA&image_hotlink_template=https://i3.wp.com/${host}${pathname}?code=xxxxxxxxxxxxx
```
现在 已完成推送代码至远端代码库，经查看 远端代码库中 相应代码已经替换成功，如下:
```
/weibo/user/${uid}/readable=1&authorNameBold=1&showAuthorInTitle=0&showAuthorInDesc=1&showAuthorAvatarInDesc=0&showAuthorAvatarInDesc=0&showEmojiForRetweet=1&showRetweetTextInTitle=0&addLinkForPics=1&showTimestampInDescription=0&showEmojiInDescription=1&showLinkIconInDescription=0&showLinkIconInDescription=0&key=geRSAaJrwdXyDA&image_hotlink_template=https://i3.wp.com/${host}${pathname}
```
我已通过自定义规则同步至chrome浏览器插件(F12看到已经下载成功)
通过weibo web页面，Radar已经检测到对应规则。
现在问题是 
最后一段
```
https://i3.wp.com/${host}${pathname}
```
在使用 Radar 插件 转入 ttrss 过程中，代码中的花括号，均被转换成 %7B %7D。
我尝试了各种方法包括加入 \变为
```
https://i3.wp.com/$\{host}$\{pathname}
```
均无法解决转义问题，请帮忙检查一下，哪里出现问题？

**Comment by DIYgod** [comment]
`${host}` 和 `${pathname}` 是什么

**Comment by DIYgod** [comment]
似乎是 image_hotlink_template 功能有问题，你能手动构建出一个可生效的链接么？

code 见：https://docs.rsshub.app/zh/install/config#%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E9%85%8D%E7%BD%AE

**Comment by 9k001** [comment]
> 似乎是 image_hotlink_template 功能有问题，你能手动构建出一个可生效的链接么？
> 
> code 见：https://docs.rsshub.app/zh/install/config#%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E9%85%8D%E7%BD%AE

我进行了如下两个操作
1. 带有 image_hotlink_template  参数。从Rader触发到并点击"复制"后。我手动将该链接经过后的花括号(即  %7B %7D)再换回来(即{}) 该链接无法访问 报错误链接
2. 去掉  image_hotlink_template 参数。 可正常生成链接访问。该链接无任何花括号及其转义后的  %7B %7D。

**Comment by 9k001** [comment]
> 似乎是 image_hotlink_template 功能有问题，你能手动构建出一个可生效的链接么？
> 
> code 见：https://docs.rsshub.app/zh/install/config#%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6%E9%85%8D%E7%BD%AE

又复盘了整个操作 理解这个code其实是为了key不暴露在页面上进行的优化。我又着手进行了测试
发现问题出现在这里
```
http://{url}/weibo/user/{uid}/{routeParams}&image_hotlink_template=https://i3.wp.com/${host}${pathname}
```
注意 此处 **image_hotlink_template** 前的连接符号为 **&** 这个是错误路径 修改该连接符为 **?** 则是正常可以访问的路径。
但是这个路径没办法被 Radar 识别。
正常按照规则，上述通过Radar订阅到TTRSS的完整的有效的URL应为
```
http://{url}/weibo/user/{uid}/{routeParams}?image_hotlink_template=https://i3.wp.com/${host}${pathname}?code={code}
```
但是在实际使用过程中 Radar 无法在博主页面检测到路由。
据我猜测，可能是路由分隔符识别有一些小小的逻辑上的bug ?

**Comment by 9k001** [comment]
我使用
HOTLINK_TEMPLATE 参数配合
# 多媒体处理特性控制
ALLOW_USER_HOTLINK_TEMPLATE=true
# 图片处理路由
HOTLINK_INCLUDE_PATHS='/weibo'
解决了当前问题
