### ISSUE TITLE
更新规则居然要 5 个小时

### ISSUE THREAD

**Issue by AiraNadih** [DIYgod/RSSHub-Radar#754]
Firefox 的扩展现在可以更新规则，这是 3 年来的重大更新。
但每次更新需要 5 小时，这时长也太离谱了吧。😂

**Comment by LakeishaKowalczyk** [comment]
那是更新间隔，不是更新耗时

话说这波更新真牛逼，是火狐审核标准变了嘛

**Comment by LakeishaKowalczyk** [comment]
识字不，中文认识伐，知道什么叫「31 min 前」,「 4h 28min 后」不？

![image](https://github.com/DIYgod/RSSHub-Radar/assets/14090545/56da2df6-be7c-459e-857c-3569334499a5)

过于无知，暴露智商

**Comment by AiraNadih** [comment]
好吧，是我傻逼了。

可是这进度条也太有迷惑性了。

我更新后一打开，忘了进度条是空的还是没显示的状态。于是点击了「立即更新」。

结果还以为那个进度条是更新的进度。
