### ISSUE TITLE
请修改规则更新相关的页面元素，以较少迷惑性和误导性

### ISSUE THREAD

**Issue by AiraNadih** [DIYgod/RSSHub-Radar#755]
正如 #754 里所说的，我认为目前的页面元素布局和设计有很大的迷惑性和误导性，所以想提出一些修改建议：

1. 将「立即更新」按钮、进度条和更新时间信息在视觉上进行更明显的区分
2. 进度条应该用于表示当前的更新状态，如使用不同颜色或标签明确显示“正在更新”、“已完成”等状态
3. 使用更直观的方式表达更新时间，例如“距离下次自动更新还有 xx小时xx分钟”以及“上次更新于 xx小时xx分钟前”，以避免歧义

**Comment by DIYgod** [comment]
v2.0.0 已重新设计
