### ISSUE TITLE
本地阅读器订阅设置不合理

### ISSUE THREAD

**Issue by senran9999** [DIYgod/RSSHub-Radar#757]
<img width="709" alt="image" src="https://github.com/DIYgod/RSSHub-Radar/assets/70112836/6923702d-992a-4c8f-9e7a-002e0be35500">
选择本地阅读器后，右侧对话框内无法更改，导致本地阅读器认读错误。每次还得手动删除，建议这里可以更改

**Comment by DIYgod** [comment]
正常阅读器都是用这个协议，你用的是什么阅读器

**Comment by glassywater** [comment]
> 正常阅读器都是用这个协议，你用的是什么阅读器

想问下有哪些本地阅读器支持feed协议，可以推荐一下吗，我本地的fluent reader ,阅读助理，thunderbird都没法打开

**Comment by senran9999** [comment]
那个 feeds://位置可以自己调整即可





glassywater ***@***.***>于2023年12月16日 周六13:09写道：

**Comment by DIYgod** [comment]
> 想问下有哪些本地阅读器支持feed协议，可以推荐一下吗，我本地的fluent reader ,阅读助理，thunderbird都没法打开

我用的 Reeder 是可以的，`feed://` 是一种惯用的方案

<img width="588" alt="image" src="https://github.com/DIYgod/RSSHub-Radar/assets/8266075/00696a46-6611-4f31-a5ab-6e8d5496c800">



> 那个 feeds://位置可以自己调整即可

具体是什么样的需求，想调整成什么内容

**Comment by senran9999** [comment]
> 2023年12月16日 15:57，DIYgod ***@***.***> 写道：
> 
> 
> 想问下有哪些本地阅读器支持feed协议，可以推荐一下吗，我本地的fluent reader ,阅读助理，thunderbird都没法打开
> 
> 我用的 Reeder 是可以的，feed:// 是一种惯用的方案
> 
> image.png (view on web) <https://github.com/DIYgod/RSSHub-Radar/assets/8266075/00696a46-6611-4f31-a5ab-6e8d5496c800>
> 那个 feeds://位置可以自己调整即可
> 
> 具体是什么样的需求，想调整成什么内容
> 
如果有有feeds://就会在正常的rss链接前面强行加上feeds://,这就意味着无法订阅，所以，只要可以删除这个feeds即可
￼

**Comment by DIYgod** [comment]
没有 `feeds://` 是无法调起本地阅读器的
