### ISSUE TITLE
无法读取Access Key

### ISSUE THREAD

**Issue by u9E9F** [DIYgod/RSSHub-Radar#758]
似乎2.0.0后Access Key无法被正常读取

这是我的设置

![image](https://github.com/DIYgod/RSSHub-Radar/assets/770738/e4b35987-9c5e-4fc7-a777-18d36d9d192d)

然后， RSSHub Radar始终无法生产正常的RSS feed
`http://..../bilibili/user/video/47383116`

是我设置错误还是怎么?

**Comment by DIYgod** [comment]
dev 已修复，将在 v2.0.1 发布 393b003a1e36daac9d17e24e573f01d7e1f49473
