### ISSUE TITLE
是否考虑添加一个 RSS 预览的功能 

### ISSUE THREAD

**Issue by akynazh** [DIYgod/RSSHub-Radar#770]
1. 开发 rsshub 新路由时，浏览器访问路由后可以直接预览一下会很有用
2. 访问一个 feed 时（比如 feed.xml, index.xml）,如果可以检测到并进行预览和订阅会很有用
4. 虽然可以通过其他扩展实现，但是 all in one 的感觉会很好！

**Comment by DIYgod** [comment]
你说的预览是指什么？

至于检测 feed，我尝试了一下，Chrome 似乎限制了在 feed 页面加载插件脚本，暂时没什么办法

**Comment by akynazh** [comment]
> 你说的预览是指什么？
> 
> 至于检测 feed，我尝试了一下，Chrome 似乎限制了在 feed 页面加载插件脚本，暂时没什么办法

就是像 inoreader 那样的扩展，你可以试一下，浏览器访问一个 feed.xml 可以把文章直接渲染出来，这样可以看到大概写的怎么样而不用具体订阅后才看得到结构

**Comment by DIYgod** [comment]
Here it is c31e21d1a2b7588e36440daff50e9222314ae068
