### ISSUE TITLE
本地阅读器(NetNewsWired)订阅地址生成有问题

### ISSUE THREAD

**Issue by akynazh** [DIYgod/RSSHub-Radar#771]
点击“本地阅读器”进行订阅，如图所示，多了 "http///" 这个前缀，不知道是不是 NetNewsWire 自己的问题

<img width="480" alt="Snipaste_2023-12-16_21-19-08" src="https://github.com/DIYgod/RSSHub-Radar/assets/78672905/bff38d48-9c10-4a84-b272-94b87222d0a7">

浏览器：Microsoft Edge 版本 117.0.2045.31 (正式版本) (arm64)
软件：NetNewsWire 6.1.5b1

**Comment by DIYgod** [comment]
It's a bug, has been fixed in a65da8c4689c27780ae9a4c38f73ca87be2106ad
