### ISSUE TITLE
feed:// 的订阅地址订阅到本地阅读器有问题

### ISSUE THREAD

**Issue by akynazh** [DIYgod/RSSHub-Radar#772]
<img width="444" alt="Snipaste_2023-12-17_11-57-45" src="https://github.com/DIYgod/RSSHub-Radar/assets/78672905/6654cc6c-9932-4a27-aeee-35ac0894c480">

<img width="480" alt="Snipaste_2023-12-17_11-57-51" src="https://github.com/DIYgod/RSSHub-Radar/assets/78672905/08f3d523-92f7-4f01-a62e-56237c052ddb">

如图所示，feed://* 的地址订阅到本地阅读器后前面多了 http:// 这个前缀。

插件：2.0.1
浏览器：Microsoft Edge 版本 117.0.2045.31 (正式版本) (arm64)

**Comment by DIYgod** [comment]
Fixed in fd3be6942175f9799d83af77dbd564c1daea8c3a
