### ISSUE TITLE
手动安装插件时报content.js不是UTF-8编码的问题

### ISSUE THREAD

**Issue by good1uck** [DIYgod/RSSHub-Radar#79]
![image](https://user-images.githubusercontent.com/23480644/65681499-91a38700-e08b-11e9-9bfd-cc53bf8105b5.png)

即使是用VSCODE转编码为UTF-8后也是一直报这个问题。

文件目录应该没有问题，是用NPM装的（无ERROR）
![image](https://user-images.githubusercontent.com/23480644/65681593-d0d1d800-e08b-11e9-8935-152993f281f3.png)

**Comment by DIYgod** [comment]
完全没有头绪...试试 releases 里打包好的？ https://github.com/DIYgod/RSSHub-Radar/releases

**Comment by AiPacino** [comment]
我也复现了，mac os，dist编译后
未能成功加载扩展程序
文件
~/桌面/mini/RSSHub-Radar/dist
错误
无法为内容脚本加载“content.js”文件。该文件采用的不是 UTF-8 编码。
无法加载清单。

**Comment by fuchengjx** [comment]
window 也复现了这个bug(使用npm安装的)，content.js不是UTF-8编码。  但是使用yarn安装依赖并打包，就没有这个问题了。应该是npm安装的依赖里有问题。
