### ISSUE TITLE
部分小众b站up主的”current up主投稿“ rss搜索不到

### ISSUE THREAD

**Issue by zhetian7499** [DIYgod/RSSHub-Radar#817]
部分小众b站up主的”current up主投稿“ rss能生成但是feedly 搜索/添加 不了，比如这位：https://space.bilibili.com/480567097。但是没发现有up主”current up主动态“这一项搜索/添加 不了；
我不太了解这其中的原理，不知道是否能解决。
我的需求是添加up主的投稿视频，而不是动态，所以故有此问
十分谢谢！

**Comment by DIYgod** [comment]
Q: Can I use the demo instance？

A: [rsshub.app](https://rsshub.app/) is the demo instance provided, running the latest build of RSSHub from master branch, the cache is set 120 minutes and it's free to use. However, if you see an badge 🚨 Strict anti-crawling for route, this means popular websites such as Facebook etc. may pose a request quota on individual IP address, which means it can get unreliable from time to time for the demo instance. You are encouraged to [host your own RSSHub instance](https://docs.rsshub.app/install/) to get a better usability.
