### ISSUE TITLE
( ´･･)ﾉ(._.`) No RSS found

### ISSUE THREAD

**Issue by dossma** [DIYgod/RSSHub-Radar#831]
When clicking on the RssHub Radar panel, the following error occurs:

```
( ´･･)ﾉ(._.`) No RSS found
Join [RSSHub](https://docs.rsshub.app/) to make everything RSSible
```
Do I do something wrong?

**Comment by DIYgod** [comment]
Not all pages will be recognized as having RSS, only pages that provide RSS or are supported by [RSSHub](https://github.com/DIYgod/RSSHub) will be recognized.
