### ISSUE TITLE
Firefox无法更新规则，且性能占用很大

### ISSUE THREAD

**Issue by JamYiz** [DIYgod/RSSHub-Radar#835]
![图片](https://github.com/DIYgod/RSSHub-Radar/assets/44351690/b4a16acf-c697-4b80-a24f-e7d204e6bf4b)

此处规则一直为0，而且更新规则会占用很多性能，导致浏览器十分卡顿
![图片](https://github.com/DIYgod/RSSHub-Radar/assets/44351690/007fcae7-f727-4d3f-86af-d8da6d93a2ff)

**Comment by DIYgod** [comment]
我无法复现你的问题，请问你的浏览器版本和插件版本都是多少

**Comment by JamYiz** [comment]
我的Firefox版本为122.0，插件版本是2.0.8

**Comment by JamYiz** [comment]
似乎当手动触发一次更新规则后，就会出现以上情况。

**Comment by SettingDust** [comment]
复现了，有些问题，`parseRules` 返回了 string，然后就直接遍历 char 了XDDD
