### ISSUE TITLE
[问题反馈] 本地化不全

### ISSUE THREAD

**Issue by Vstory** [DIYgod/RSSHub-Radar#843]
如下图所示，该位置英文未本地化成中文。
![image](https://github.com/DIYgod/RSSHub-Radar/assets/20795557/d43da800-93d4-46e6-a09a-20afb6c4979e)

**Comment by DIYgod** [comment]
Fixed in 3343b05f9e8d8eebe7641281d36adcd55cbd58dd

I have released v2.0.10 and submit it for store review. If there are any further issues, please reopen this issue.
