### ISSUE TITLE
v2.0.10 cannot match RSS on Chrome

### ISSUE THREAD

**Issue by JimenezLi** [DIYgod/RSSHub-Radar#850]
I upgraded my RSSHub Radar to v2.0.10, and it can't match any RSS on Chrome. It works fine with Firefox.

Here is an example, the left one is v2.0.8, the right one is v2.0.10.

![image](https://github.com/DIYgod/RSSHub-Radar/assets/75196426/06547645-1f13-4d97-8908-c804e0e0c595)

My browser is Chrome 121.0.6167.86 on Windows 10

**Comment by DIYgod** [comment]
Thanks for your report, it has been fixed in 1d7a7d04cb753af252e06047739a50e978bd40f2 and I'm releasing v2.0.11
