### ISSUE TITLE
Firefox 上怎么调试 Radar 规则？

### ISSUE THREAD

**Issue by SettingDust** [DIYgod/RSSHub-Radar#851]
https://docs.rsshub.app/zh/joinus/new-radar#%E8%B0%83%E8%AF%95-radar-%E8%A7%84%E5%88%99

没看到有文本框，是 v2 没了吗

EDIT: Edge 也没有文本框

**Comment by DIYgod** [comment]
重构时候去掉了，现在可以通过本地代理出一个地址然后填到 `Remote radar rules URL` 来调试
