### ISSUE TITLE
无法检测到当前Github Issues的订阅

### ISSUE THREAD

**Issue by ItsFated** [DIYgod/RSSHub-Radar#953]
之前我记得是有直接订阅当前Issues方式，现在没有了。如下图：
![image](https://github.com/DIYgod/RSSHub-Radar/assets/13051752/4daae779-1dd8-4820-b613-cc4ab0b866d1)
订阅到RefreshRSS中的效果（这个是以前Radar插件自己生成的，不是我手动改的标题和源）：
![image](https://github.com/DIYgod/RSSHub-Radar/assets/13051752/7cb140a1-df11-4f7e-b064-985c5fac11d7)
是以后都要手动添加了吗
![0128ED5D](https://github.com/DIYgod/RSSHub-Radar/assets/13051752/958f5422-def3-4049-8beb-480966e11147)

**Comment by Qixingchen** [comment]
已合并,等待官方实例更新到合并版本后更新下radra规则

**Comment by ItsFated** [comment]
> 已合并,等待官方实例更新到合并版本后更新下radra规则

大佬牛逼

**Comment by ItsFated** [comment]
已经有了，感谢
