### ISSUE TITLE
反馈一个错误

### ISSUE THREAD

**Issue by LisonFan** [DIYgod/RSSHub-Radar#961]
https://rsshub.app/juejin/trending/all/monthly

![image](https://github.com/DIYgod/RSSHub-Radar/assets/9424775/927f6516-c0f7-4ae1-ad8e-f64d40a510b6)

**Comment by DIYgod** [comment]
This is a bug of RSSHub, can you submit an issue [here]((https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&projects=&template=bug_report_zh.yml))?
