### ISSUE TITLE
inoreader接口不起作用

### ISSUE THREAD

**Issue by lxxself** [DIYgod/RSSHub-Radar#97]
https://www.inoreader.com/?add_feed=xxx 这个形式不起作用了，试了下变成这个了https://www.inoreader.com/feed/xxx 
还请确认下，或者是我使用姿势不对

**Comment by DIYgod** [comment]
我试了下两个都是可以的，不起作用的具体表现是什么

**Comment by lxxself** [comment]
![image](https://user-images.githubusercontent.com/8406766/68080573-889b9780-fe39-11e9-93b6-602bbc957dfa.png)

**Comment by lxxself** [comment]
https://cdn.nlark.com/yuque/0/2019/gif/117381/1572757225977-assets/web-upload/0cb1f2cf-3f6d-4320-88d8-866cc06a33fe.gif
