### ISSUE TITLE
订阅到本地阅读器时前面多出了http://

### ISSUE THREAD

**Issue by vansun1992** [DIYgod/RSSHub-Radar#98]
前面有两个http://导致订阅不成功，需要手动删除一个。

本地阅读器：reader 3

订阅账号：feedly

直接在网页端feedly上不会有这个问题，不过有些rss链接不好识别。

**Comment by DIYgod** [comment]
哪个页面？

**Comment by vansun1992** [comment]
？RSSHub-Radar的插件问题，Mac环境下，几乎所有试过的输出页面都会有这个问题，自带rss的网站

在 2019-10-25 17:38:38，"DIYgod" <notifications@github.com> 写道：


哪个页面？

**Comment by DIYgod** [comment]
无法复现
